### ISSUE TITLE
sudo ./install.sh doesn't install

### ISSUE THREAD

**Issue by mmcmonster** [atar-axis/xpadneo#353] opened 2022-05-09 16:23 UTC
## Version of xpadneo
Current version (downloaded via git)

## Controller Model
N/A

## Severity / Impact
* [ ] I've read the docs and the bug reporting instructions
* [ ] I've applied the latest firmware update to the controller
* [X] It does not work at all
* [ ] It used to work in a previous version
* [ ] It mostly works but sometimes it doesn't
* [ ] I found a work-around
* [ ] I probably didn't figure it all out but it's too early to give up
* [ ] I don't know how to ... 
* [ ] It's too complicated
* [ ] Fantastic work but ... 
* [ ] I can code and I want to help

## Describe the Bug
(Starting from scratch)
$ git clone https://github.com/atar-axis/xpadneo.git
$ cd ~/xpadneo && sudo ./install.sh
sed: can't read lib/../VERSION: No such file or directory

## Steps to Reproduce
As above

## Expected Behavior
Installation

## System Information
Linux Mint 20.3 (Una) fresh installation

# uname -a
Linux basement 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)

```
xxd: /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor: No such file or directory
4294967295 0

## Controller and Bluetooth Information
N/A

**Comment by kakra** [comment] 2022-05-09 16:46
Please run `git clone` as root, too.

Duplicate of #346

**Closed by kakra** 2022-05-09 16:46 UTC
