### ISSUE TITLE
sed: can't read lib/../VERSION: No such file or directory

### ISSUE THREAD

**Issue by blitz-research** [atar-axis/xpadneo#358] opened 2022-05-14 22:52 UTC
Ok, my seemingly never ending quest to get my bluetooth xbox controller working on Manjaro has led me here....

I'm pretty sure I've installed everything I need via pacman:

    sudo pacman -S dkms linux-headers bluez bluez-utils

This ending up asking me:

    :: There are 12 providers available for linux-headers:
    :: Repository core
       1) linux414-headers  2) linux419-headers  3) linux49-headers  4) linux510-headers  5) linux515-headers
       6) linux516-headers  7) linux517-headers  8) linux518-headers  9) linux54-headers
    :: Repository community
       10) linux515-rt-headers  11) linux516-rt-headers  12) linux517-rt-headers

    Enter a number (default=1): 1

...I have no idea what this means so I selected the default, 1.

Next I cloned the xpadneo repository, but when it comes to the "sudo ./install.sh" bit I get:

    sed: can't read lib/../VERSION: No such file or directory

And, well, it's sort of right, there is no VERSION file in that location.

Help?!?

Bye,
Mark

**Comment by kakra** [comment] 2022-05-15 01:28
Duplicate of #346

**Closed by kakra** 2022-05-15 01:28 UTC
