### ISSUE TITLE
Dropped into Busybox shell 000

### ISSUE THREAD

**Issue by CodyMarkix** [atar-axis/xpadneo#436] opened 2023-07-22 17:42 UTC
## Version of xpadneo
Latest commit on master branch [(this one)](https://github.com/atar-axis/xpadneo/commit/9b3b6968304d75faca00d1cead63f89e8895195f)

## Controller Model

- [x] Xbox One S controller
- [ ] Xbox Elite 2 controller
- [ ] Xbox Series X|S controller
- [ ] Other:

### Connection mode

- [x] Bluetooth connection
- [ ] USB cable (not yet supported)
- [ ] Xbox Dongle connection (not yet supported)

## Installed Software

- [ ] Anti-Micro (may affect button mappings)
- [ ] OpenRGB (may mess up mappings and rumble stability)
- [x] Steam Input (enabled by default via Steam Desktop client)
- [ ] Steam Link (usually via Raspberry Pi or other micro computers)
- [ ] devices with QMK firmware (may affect udev rules, similar to OpenRGB)
- [ ] netstick (shares input devices via network similar to Steam Link)
- [ ] xboxdrv (user-space gamepad driver)
- [ ] xone (kernel-space gamepad driver using the Xbox dongle or USB)
- [ ] xow (alternative driver using the Xbox dongle)

## Protocol Information

Please help us identify at which layer the problem can be found if you want
to report mapping errors or if the controller fails to be detected:

- [ ] Steam Proton games are having issues
- [ ] Steam Linux-native games are having issues
    - [ ] I don't use Steam or did not try
- [ ] games running through Lutris, wine and/or Bottles are having issues
    - [ ] I don't use Lutris, Bottles, wine or did not try
- [ ] Linux-native games are having issues
    - [ ] I don't use native games or did not try
- [ ] Other software is having issues (describe software and issues below)
- [ ] Running `evtest` is showing issues (describe the issues below)
    - Keep in mind that `BTN_NORTH` and `BTN_WEST` are intentionally swapped
- [ ] Running `jstest` is showing issues (describe the issues below)
    - [ ] I don't have this tool or don't know how to use it
- [ ] Running `gamepad-tool` is showing issues (post console output below)
    - [ ] I don't have this tool

Please describe how it is failing below in the next sections.

## Severity / Impact

- [ ] I've read the docs and the bug reporting instructions
- [ ] I've applied the latest firmware update to the controller
- [ ] I've tried disabling or running without above mentioned software
- [x] It does not work at all
- [ ] It used to work in a previous version
- [ ] It mostly works but sometimes it doesn't
- [ ] I found a work-around
- [ ] I probably didn't figure it all out but it's too early to give up
- [ ] I don't know how to ... 
- [ ] It's too complicated
- [ ] Fantastic work but ... 
- [ ] I can code and I want to help

## Describe the Bug

After installing xpadneo and rebooting my machine, it takes longer to boot up, it gets to showing the Plymouth boot screen and then drops into an emergency busybox shell

## Steps to Reproduce

- Install xpadneo
- Reboot

## Expected Behavior

Everything would work as normal

## System Information

```console
# uname -a
# Pop!_OS 22.04 root 6.2.6something amd64
```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)

```

## Additional Context

Rebooting into an automatically made backup of the kernel works fine (except half the kernel modules are missing)

**Comment by kakra** [comment] 2023-07-23 00:11
We've seen this before with Pop OS if I remember correctly. Is there any log you can get?

**Comment by kakra** [comment] 2023-07-23 00:13
Closing as duplicate of https://github.com/atar-axis/xpadneo/issues/425

**Closed by kakra** 2023-07-23 00:13 UTC
