### ISSUE TITLE
Gamesir T4 Nova Lite, Rumble not working

### ISSUE THREAD

**Issue by Gustavo17pacheco** [atar-axis/xpadneo#518] opened 2024-12-22 12:27 UTC
## Version of xpadneo

Latest on xpadneo-dkms package 

## Controller Model

- [ ] Xbox One S controller
- [ ] Xbox Elite 2 controller
- [X] Xbox Series X|S controller
- [ ] Other:

### Connection mode

- [X] Bluetooth connection
- [ ] USB cable (not yet supported)
- [ ] Xbox Dongle connection (not yet supported)

## Installed Software

- [ ] Anti-Micro (may affect button mappings)
- [ ] OpenRGB (may mess up mappings and rumble stability)
- [X] Steam Input (enabled by default via Steam Desktop client)
- [ ] Steam Link (usually via Raspberry Pi or other micro computers)
- [ ] devices with QMK firmware (may affect udev rules, similar to OpenRGB)
- [ ] netstick (shares input devices via network similar to Steam Link)
- [ ] xboxdrv (user-space gamepad driver)
- [ ] xone (kernel-space gamepad driver using the Xbox dongle or USB)
- [ ] xow (alternative driver using the Xbox dongle)

## Protocol Information

Please help us identify at which layer the problem can be found if you want
to report mapping errors or if the controller fails to be detected:

- [X] Steam Proton games are having issues
- [X] Steam Linux-native games are having issues
    - [ ] I don't use Steam or did not try
- [X] games running through Lutris, wine and/or Bottles are having issues
    - [ ] I don't use Lutris, Bottles, wine or did not try
- [X] Linux-native games are having issues
    - [ ] I don't use native games or did not try
- [X] Other software is having issues (describe software and issues below)
- [ ] Running `evtest` is showing issues (describe the issues below)
    - Keep in mind that `BTN_NORTH` and `BTN_WEST` are intentionally swapped
- [ ] Running `jstest` is showing issues (describe the issues below)
    - [ ] I don't have this tool or don't know how to use it
- [ ] Running `gamepad-tool` is showing issues (post console output below)
    - [ ] I don't have this tool

Please describe how it is failing below in the next sections.

## Severity / Impact

- [X] I've read the docs and the bug reporting instructions
- [X] I've applied the latest firmware update to the controller
- [X] I've tried disabling or running without above mentioned software
- [ ] It does not work at all
- [ ] It used to work in a previous version
- [ ] It mostly works but sometimes it doesn't
- [ ] I found a work-around
- [ ] I probably didn't figure it all out but it's too early to give up
- [ ] I don't know how to ... 
- [ ] It's too complicated
- [ ] Fantastic work but ... 
- [ ] I can code and I want to help

## Describe the Bug

I've download xpadneo-dkms on Arch and built from source on Ubuntu, but my Gamesir Nova Lite's rumble will not work. I tried adding quirks, but that doesn't seem to work.

[46607.934139] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B13.000D/input/input46
[46607.934255] microsoft 0005:045E:0B13.000D: input,hidraw3: BLUETOOTH HID v0.23 Gamepad [Xbox Wireless Controller] on 00:1a:7d:da:71:12
[46607.988144] xpadneo 0005:045E:0B13.000D: classic Bluetooth firmware version 0.23, please upgrade for better stability
[46607.988147] xpadneo 0005:045E:0B13.000D: pretending XB1S Windows wireless mode (changed PID from 0x0B13 to 0x028E)
[46607.988149] xpadneo 0005:045E:0B13.000D: working around wrong SDL2 mappings (changed version from 0x00000023 to 0x00001130)
[46607.988151] xpadneo 0005:045E:0B13.000D: report descriptor size: 283 bytes
[46607.988152] xpadneo 0005:045E:0B13.000D: fixing up Rx axis
[46607.988153] xpadneo 0005:045E:0B13.000D: fixing up Ry axis
[46607.988154] xpadneo 0005:045E:0B13.000D: fixing up Z axis
[46607.988155] xpadneo 0005:045E:0B13.000D: fixing up Rz axis
[46607.988156] xpadneo 0005:045E:0B13.000D: fixing up button mapping
[46607.988293] xpadneo 0005:045E:0B13.000D: enabling compliance with Linux Gamepad Specification
[46607.988323] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B13.000D/input/input47
[46607.988557] xpadneo 0005:045E:0B13.000D: input,hidraw3: BLUETOOTH HID v11.30 Gamepad [Xbox Wireless Controller] on 00:1a:7d:da:71:12
[46607.988562] xpadneo 0005:045E:0B13.000D: controller quirks: 0x00000050
[46608.977724] xpadneo 0005:045E:0B13.000D: Xbox Wireless Controller [ac:20:06:3c:f5:84] connected
[46610.321871] input: Microsoft X-Box 360 pad 0 as /devices/virtual/input/input48

I've tried using both 00:1a:7d:da:71:12 and ac:20:06:3c:f5:84 as MAC addresses on /etc/modprobe.conf but I still do not get rumble.
## Steps to Reproduce

Install xpadneo
Try using any game or test with rumble

## Expected Behavior

For my controller to vibrate

## System Information

```console
# uname -a
Linux gustavo-arch 6.12.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 x86_64 GNU/Linux

```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)
4294967295 0
```

## Controller and Bluetooth Information

[xpadneo-btmon.txt](https://github.com/user-attachments/files/18221817/xpadneo-btmon.txt)
[xpadneo-dmesg.txt](https://github.com/user-attachments/files/18221818/xpadneo-dmesg.txt)
[xpadneo-lsusb.txt](https://github.com/user-attachments/files/18221819/xpadneo-lsusb.txt)

**Comment by kakra** [comment] 2024-12-22 13:44
You didn't log the version, neither you added a package version. I'm pretty sure you are on v0.9.6, the problem will be fixed in v0.9.7 and is fixed in master.

Closing as duplicate of https://github.com/atar-axis/xpadneo/issues/484

**Closed by kakra** 2024-12-22 13:44 UTC
