### ISSUE TITLE
kmod not compiling after upgrading to kernel 6.12.4-200.fc41.x86_64 (Fedora 41)

### ISSUE THREAD

**Issue by Maddosaurus** [atar-axis/xpadneo#516] opened 2024-12-17 18:42 UTC
## Version of xpadneo
xpadneo-0.9.6-1.fc41.x86_64

## Controller Model
- [ ] Xbox One S controller
- [x] Xbox Elite 2 controller
- [ ] Xbox Series X|S controller
- [ ] Other:

### Connection mode

- [x] Bluetooth connection
- [ ] USB cable (not yet supported)
- [ ] Xbox Dongle connection (not yet supported)

## Installed Software

- [ ] Anti-Micro (may affect button mappings)
- [ ] OpenRGB (may mess up mappings and rumble stability)
- [x] Steam Input (enabled by default via Steam Desktop client)
- [ ] Steam Link (usually via Raspberry Pi or other micro computers)
- [ ] devices with QMK firmware (may affect udev rules, similar to OpenRGB)
- [ ] netstick (shares input devices via network similar to Steam Link)
- [ ] xboxdrv (user-space gamepad driver)
- [ ] xone (kernel-space gamepad driver using the Xbox dongle or USB)
- [ ] xow (alternative driver using the Xbox dongle)

## Protocol Information

Please help us identify at which layer the problem can be found if you want
to report mapping errors or if the controller fails to be detected:

- [ ] Steam Proton games are having issues
- [ ] Steam Linux-native games are having issues
    - [ ] I don't use Steam or did not try
- [ ] games running through Lutris, wine and/or Bottles are having issues
    - [ ] I don't use Lutris, Bottles, wine or did not try
- [ ] Linux-native games are having issues
    - [ ] I don't use native games or did not try
- [x] Other software is having issues (describe software and issues below)
- [ ] Running `evtest` is showing issues (describe the issues below)
    - Keep in mind that `BTN_NORTH` and `BTN_WEST` are intentionally swapped
- [ ] Running `jstest` is showing issues (describe the issues below)
    - [ ] I don't have this tool or don't know how to use it
- [ ] Running `gamepad-tool` is showing issues (post console output below)
    - [ ] I don't have this tool

The kernel module fails to compile when `akmods` is invoked

Please describe how it is failing below in the next sections.

## Severity / Impact

- [x] I've read the docs and the bug reporting instructions
- [ ] I've applied the latest firmware update to the controller
- [ ] I've tried disabling or running without above mentioned software
- [ ] It does not work at all
- [x] It used to work in a previous version
- [ ] It mostly works but sometimes it doesn't
- [ ] I found a work-around
- [ ] I probably didn't figure it all out but it's too early to give up
- [ ] I don't know how to ... 
- [ ] It's too complicated
- [ ] Fantastic work but ... 
- [ ] I can code and I want to help

## Describe the Bug
After upgrading to kernel 6.12.4-200.fc41.x86_64 on Fedora 41, the kernel module fails to compile, leading to the module not being loaded, therefore the controller not using xpadneo.
Before the system update, everything was working as intended and the kmod was able to be compiled.

## Steps to Reproduce
(Don't know exactly besides) upgrading to latest kernel and system package versions

## Expected Behavior
Kernel module should compile and be loaded

## System Information

```console
# uname -a
Linux  6.12.4-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Dec  9 20:01:35 UTC 2024 x86_64 GNU/Linux
```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)
xxd: /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor: No such file or directory
```

## Controller and Bluetooth Information
Skipped, as the problem lies before even attempting a connection.

## Additional Context
Output of a manual akmods command:
```console
sudo akmods --force --kernels 6.12.4-200.fc41.x86_64
Checking kmods exist for 6.12.4-200.fc41.x86_64            [  OK  ]
Building and installing xpadneo-kmod                       [FAILED]
Building rpms failed; see /var/cache/akmods/xpadneo/0.9.6-1-for-6.12.4-200.fc41.x86_64.failed.log for details
```
I have attached the mentioned `failed.log`:

[0.9.6-1-for-6.12.4-200.fc41.x86_64.failed.log](https://github.com/user-attachments/files/18169960/0.9.6-1-for-6.12.4-200.fc41.x86_64.failed.log)

**Comment by kakra** [comment] 2024-12-17 21:03
Closing as duplicate of https://github.com/atar-axis/xpadneo/issues/498, v0.9 backport queued in https://github.com/atar-axis/xpadneo/pull/508.

**Closed by kakra** 2024-12-17 21:03 UTC
