### ISSUE TITLE
Error when installing on OSMC

### ISSUE THREAD

**Issue by chivigoku** [atar-axis/xpadneo#50] opened 2018-11-02 13:24 UTC
Hi guys,

I´ve installed this driver over Rapsbian several times and it worked properly.
However, over OSMC I´m not able to do it works.

1. sudo apt-get install dkms raspberrypi-kernel-headers (does not work)
You must run
sudo apt-get install dkms rbp2-kernel-$'(uname -r)'

2. once you run ./install.sh 
this got an error related with headers that can´t be found

**Error! echo
Your kernel headers for kernel 4.14.34-6-osmc cannot be found at
/lib/modules/4.14.34-6/build or /lib/modules/4.14.34-6/source.**

3. Actually OSMC does not recommend install DKMS so I assume it´s mandatory in this driver.

I´m working on 4.14.34-6-osmc (lastest version so far)

I´d like to show further info but I´m not at home.
My question is, has anyone made this driver work over OSMC?

Regards,
ChIvI

**Comment by lowlyocean** [comment] 2018-11-02 13:34
did you also try `sudo apt-get install rbp2-headers-4.14.34-6-osmc`

**Comment by chivigoku** [comment] 2018-11-02 14:53
Hi,

I have run the command you mentioned and I got this:

osmc@osmc:~/xpadneo$ sudo apt-get install rbp2-headers-4.14.34-6-osmc
Reading package lists… Done
Building dependency tree
Reading state information… Done
Suggested packages:
module-init-tools
Recommended packages:
libc6-dev | libc-dev
The following NEW packages will be installed:
rbp2-headers-4.14.34-6-osmc
0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
Need to get 8885 kB of archives.
After this operation, 63.7 MB of additional disk space will be used.
Get:1 http://ftp.fau.de/osmc/osmc/apt stretch/main armhf rbp2-headers-4.14.34-6-osmc armhf 6 [8885 kB]
Fetched 8885 kB in 1s (6778 kB/s)
Selecting previously unselected package rbp2-headers-4.14.34-6-osmc.
(Reading database … 26526 files and directories currently installed.)
Preparing to unpack …/rbp2-headers-4.14.34-6-osmc_6_armhf.deb …
Unpacking rbp2-headers-4.14.34-6-osmc (6) …
Setting up rbp2-headers-4.14.34-6-osmc (6) …
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.14.34-6-osmc /boot/vmlinuz-4.14.34-6-osmc
Error! echo
Your kernel headers for kernel 4.14.34-6-osmc cannot be found at
/lib/modules/4.14.34-6-osmc/build or /lib/modules/4.14.34-6-osmc/source.
osmc@osmc:~/xpadneo$

**Comment by lowlyocean** [comment] 2018-11-02 14:59
First uninstall dkms and try again, then post output

**Comment by atar-axis** [comment] 2018-11-02 16:08
You can also attach your output as `.txt` (just drag it into the response field) - that's a bit more permanent than gist - or, simply use the `< >` Insert code tool

**Comment by chivigoku** [comment] 2018-11-02 17:09
Hi guys,

First of all, thanks for helping me.

Here is what I did.
Install a new OSMC (the latest release)
Install headers, DKMS, git (OSMC does not have this) and after installing xpadneo driver, it failed with same output

osmc@osmc:~/xpadneo$ ./install.sh
* copying module into /usr/src
* adding module to DKMS

Creating symlink /var/lib/dkms/hid-xpadneo/0.3.1/source ->
                 /usr/src/hid-xpadneo-0.3.1

DKMS: add completed.
* installing module (using DKMS)
Error! echo
Your kernel headers for kernel 4.14.78-2-osmc cannot be found at
/lib/modules/4.14.78-2-osmc/build or /lib/modules/4.14.78-2-osmc/source.

I have attached a txt as well with more details.

[Test1.txt](https://github.com/atar-axis/xpadneo/files/2543446/Test1.txt)

Thanks in advance @atar-axis and @lowlyocean

**Comment by lowlyocean** [comment] 2018-11-02 17:29
As I said above, do not install DKMs before you install sudo apt-get install rbp2-headers-4.14.34-6-osmc

**Comment by chivigoku** [comment] 2018-11-02 17:47
Hi buddy,

Sorry, I didn´t see that DKMs has to be after.
But, anyway, following what you said, I´m getting the same error.

Please see my input file
[test2.txt](https://github.com/atar-axis/xpadneo/files/2543560/test2.txt)

Thanks for your help

**Comment by lowlyocean** [comment] 2018-11-02 18:38
Do you also have rbp2-source-4.14.34-6-osmc?

**Comment by lowlyocean** [comment] 2018-11-02 18:41
I just noticed your errors reference a different kernel version 4.14.78-2-osmc.

Do a `dpkg -l | grep rbp2-` and make sure you have the source, headers, and kernel package for only one version installed

**Comment by atar-axis** [comment] 2018-11-02 21:47
I tried it and yes, there is no `build` or `source` directory `/lib/modules/4.14.34-6-osmc/` - don't know why.
anyway - try the following:

0. `sudo apt-get install dkms rbp2-kernel-$'(uname -r)'`
**1.** `sudo ln -s "/usr/src/rbp2-headers-4.14.34-6-osmc/" "/lib/modules/4.14.34-6-osmc/build"`
2. git clone xpadneo and change into the new directory
3. `./install.sh`

**Comment by atar-axis** [comment] 2018-11-02 22:04
I gave it a try and yes, the problem is that there is no `build` or `source` directory in `/lib/modules/4.14.34-6-osmc/` - even after installing the headers as suggested, don't know why.

anyway - we can create the missing symbolic link by hand:

0. ``sudo apt-get install dkms rbp2-kernel-`uname -r` ``
1. **``sudo ln -s "/usr/src/rbp2-headers-`uname -r`" "/lib/modules/`uname -r`/build"``**
2. git clone xpadneo and change into the new directory
3. `./install.sh`

**Comment by atar-axis** [comment] 2018-11-02 22:46
If you face any problems while pairing the gamepad, try following https://discourse.osmc.tv/t/enabling-bluetooth/711

**Comment by chivigoku** [comment] 2018-11-03 10:49
Hi Atar-axis,

It works !!!!!

But instead of 
sudo apt-get install dkms rbp2-kernel-`uname -r`
it has to be 
**sudo apt-get install dkms rbp2-headers-`uname -r`**

Now, I have a questions.
As I got installed DKMS, Could I install kernel updates?

Thanks for your help guys!!!!

Regards,

**Comment by atar-axis** [comment] 2018-11-03 11:02
Ups :sunglasses: You are welcome!

**Comment by atar-axis** [comment] 2018-11-03 15:16
> Now, I have a questions. As I got installed DKMS, Could I install kernel updates?

I think yes as long as the "kernel update" comes as a DKMS package.

**Comment by lowlyocean** [comment] 2018-11-03 15:18
`ln -s "/usr/src/rbp2-headers-`uname -r`" "/lib/modules/`uname -r`/build"`
This link will be broken after the kernel upgrades to a new version. So DKMS will complain the same way

**Comment by atar-axis** [comment] 2018-11-03 15:39
Thanks, will close it now - I updated the README accordingly

**Closed by atar-axis** 2018-11-03 15:40 UTC
Labels: testing
