### ISSUE TITLE
Building xpadneo with dkms fails on Linux kernel 6.12.0

### ISSUE THREAD

**Issue by SpidFightFR** [atar-axis/xpadneo#505] opened 2024-11-20 20:00 UTC
## Version of xpadneo
0.9.6

## Controller Model

- [ ] Xbox One S controller
- [ ] Xbox Elite 2 controller
- [x] Xbox Series X|S controller
- [ ] Other:

### Connection mode

- [x] Bluetooth connection
- [ ] USB cable (not yet supported)
- [ ] Xbox Dongle connection (not yet supported)

## Installed Software

- [ ] Anti-Micro (may affect button mappings)
- [ ] OpenRGB (may mess up mappings and rumble stability)
- [ ] Steam Input (enabled by default via Steam Desktop client)
- [ ] Steam Link (usually via Raspberry Pi or other micro computers)
- [ ] devices with QMK firmware (may affect udev rules, similar to OpenRGB)
- [ ] netstick (shares input devices via network similar to Steam Link)
- [ ] xboxdrv (user-space gamepad driver)
- [ ] xone (kernel-space gamepad driver using the Xbox dongle or USB)
- [ ] xow (alternative driver using the Xbox dongle)

## Protocol Information

Please help us identify at which layer the problem can be found if you want
to report mapping errors or if the controller fails to be detected:

- [ ] Steam Proton games are having issues
- [ ] Steam Linux-native games are having issues
    - [ ] I don't use Steam or did not try
- [ ] games running through Lutris, wine and/or Bottles are having issues
    - [ ] I don't use Lutris, Bottles, wine or did not try
- [ ] Linux-native games are having issues
    - [ ] I don't use native games or did not try
- [ ] Other software is having issues (describe software and issues below)
- [ ] Running `evtest` is showing issues (describe the issues below)
    - Keep in mind that `BTN_NORTH` and `BTN_WEST` are intentionally swapped
- [ ] Running `jstest` is showing issues (describe the issues below)
    - [ ] I don't have this tool or don't know how to use it
- [ ] Running `gamepad-tool` is showing issues (post console output below)
    - [ ] I don't have this tool

Please describe how it is failing below in the next sections.

## Severity / Impact

- [ ] I've read the docs and the bug reporting instructions
- [ ] I've applied the latest firmware update to the controller
- [ ] I've tried disabling or running without above mentioned software
- [x] It does not work at all
- [x] It used to work in a previous version
- [ ] It mostly works but sometimes it doesn't
- [ ] I found a work-around
- [ ] I probably didn't figure it all out but it's too early to give up
- [ ] I don't know how to ... 
- [ ] It's too complicated
- [ ] Fantastic work but ... 
- [ ] I can code and I want to help

## Describe the Bug
Dkms fails to build the module for this kernel version specifically, 6.11 to the latest release works.

## Steps to Reproduce
[Install it normally]
```
$ cat /var/lib/dkms/hid-xpadneo/0.9.6/build/make.log 
DKMS make.log for hid-xpadneo-0.9.6 for kernel 6.12.0_1 (x86_64)
Wed Nov 20 20:52:55 CET 2024
make: Entering directory '/usr/src/kernel-headers-6.12.0_1'
  CC [M]  /var/lib/dkms/hid-xpadneo/0.9.6/build/src/hid-xpadneo.o
/var/lib/dkms/hid-xpadneo/0.9.6/build/src/hid-xpadneo.c:1266:25: error: initialization of 'const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)' {aka 'const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)'} from incompatible pointer type 'u8 * (*)(struct hid_device *, u8 *, unsigned int *)' {aka 'unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)'} [-Werror=incompatible-pointer-types]
 1266 |         .report_fixup = xpadneo_report_fixup,
      |                         ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hid-xpadneo/0.9.6/build/src/hid-xpadneo.c:1266:25: note: (near initialization for 'xpadneo_driver.report_fixup')
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/hid-xpadneo/0.9.6/build/src/hid-xpadneo.o] Error 1
make[1]: *** [/usr/src/kernel-headers-6.12.0_1/Makefile:1936: /var/lib/dkms/hid-xpadneo/0.9.6/build/src] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/kernel-headers-6.12.0_1'

```

## Expected Behavior

The module should build, as it currently builds for older kernel versions.
Perhaps something has changed in the headers ?

## System Information

```console
# uname -a
Linux vs-desktop 6.11.8_1 #1 SMP PREEMPT_DYNAMIC Sat Nov 16 00:25:36 UTC 2024 x86_64 GNU/Linux
```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)
xxd: /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor: No such file or directory
```

**Comment by kakra** [comment] 2024-11-20 23:36
Closing as duplicate of https://github.com/atar-axis/xpadneo/issues/498

**Closed by kakra** 2024-11-20 23:36 UTC
Labels: 0 | type: bug, 1 | state: invalid
