### ISSUE TITLE
Run 'modprobe hid_xpadneo' after every boot

### ISSUE THREAD

**Issue by jefersonnavarro** [atar-axis/xpadneo#179] opened 2020-05-03 16:53 UTC
The driver seems to work fine, but every time the computer is started I must run 'modprobe hid_xpadneo' to get it to work.

What are the alternatives to make it work since boot ?

**Comment by jefersonnavarro** [comment] 2020-05-05 01:35
I found the reason.

The udev man page ( man udev ) says:

RUN{type}
           Add a program to the list of programs to be executed after processing all the rules for a specific event, depending on "type":
           "program"
               Execute an external program specified as the assigned value. If no absolute path is given, the program is expected to live in /usr/lib/udev; otherwise, the absolute path must be specified.

In the file /etc/udev/rules.d/99-xpadneo.rules there is not the path to modprobe:

RUN:="/bin/sh -c 'echo xpadneo udev: $kernel > /dev/kmsg; modprobe hid_xpadneo; echo $kernel > /sys/bus/hid/drivers/hid-generic/unbind; echo $kernel > /sys/bus/hid/drivers/microsoft/unbind; echo $kernel > /sys/bus/hid/drivers/xpadneo/bind; echo xpadneo udev: ok > /dev/kmsg'"

I do not know if every distribution puts modprobe in the same folder, but mine is in /usr/sbin/

which modprobe
/usr/sbin/modprobe

I edited the file, adding the folder and then it just worked.

**Comment by kakra** [comment] 2020-05-09 14:42
Closing as duplicate of #167

**Closed by kakra** 2020-05-09 14:42 UTC
